FROM maven:3-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests
FROM openjdk:17-jdk-slim
COPY --from=build /target/Job-Portal-0.0.1-SNAPSHOT.jar Job-Portal.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","Job-Portal.jar"]