# Build stage
FROM maven:3.9.10-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Run stage
FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /app/target/Job-Portal-0.0.1-SNAPSHOT.jar Job-Portal.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","Job-Portal.jar"]
